# Controls deployment options
[deployment]
    host = "0.0.0.0" # Set to 127.0.0.1 if you use a reverse proxy, or access it locally
    port = 8000

    # # Domain which the instance is hosted. By default it is unset.
    # # This is primary used to generate links to the instance
    # domain =

    # Enables secure cookies and forces all links
    # to openblur to use the `https://` scheme
    https = false

    # # Amount of worker openblur instances to spawn.
    # # When left at 1, openblur runs Sanic in fast mode and automatically
    # # spawns one worker per available CPU core. Set a value greater than 1 to
    # # pin an explicit worker count instead.
    # workers = 1


# # Controls behaviors pertaining to the way openblur requests Tumblr
# [openblur_backend]
    # # Timeout for requests to Tumblr's API
    # main_response_timeout = 10

    # # Timeout for fetching image responses from Tumblr
    # image_response_timeout = 30


# # Controls default user preferences
# [default_user_preferences]
#
#     # Whether blogger-truncated posts are expanded by default
#     expand_posts = false


# Controls logging behavior
#
# Use Python's numerical logging levels
# https://docs.python.org/3/howto/logging.html#logging-levels
# [logging]
    # # Sanic (Server)'s logging level'
    # sanic_logging_level = 30

    # # openblur's logging level
    # openblur_logging_level = 30

    # # openblur extractor's logging level
    # openblur_extractor_logging_level = 20


# [misc]
    # # Enable sanic's dev mode
    # dev_mode = false