services:
  openblur:
    image: quay.io/syeopite/openblur:latest
    container_name: openblur
    restart: unless-stopped
    env_file:
      - path: .env
        required: false
    ports:
      - "127.0.0.1:8000:8000" # Replace with "8000:8000" if you don't use a reverse proxy
