// Package npf renders Tumblr's Neue Post Format (NPF) into HTML.
//
// It is a Go port of syeopite/npf-renderer (the 0.13.x line that hyperblur
// pins), including the small customisations hyperblur applies on top of it.
// Rather than porting the `dominate` DOM library the output is generated by a
// tiny node tree, which keeps the formatter close to the original source.
package npf

import (
	"sort"
	"strings"
)

// Node is a minimal HTML element tree. Text nodes have an empty Tag; Raw
// controls whether their text is escaped on render.
type Node struct {
	Tag   string
	Attrs map[string]string
	Kids  []*Node
	Text  string
	Raw   bool
}

// El creates an element. Attributes are passed as alternating key/value pairs.
func El(tag string, attrs ...string) *Node {
	n := &Node{Tag: tag, Attrs: map[string]string{}}
	for i := 0; i+1 < len(attrs); i += 2 {
		n.SetAttr(attrs[i], attrs[i+1])
	}
	return n
}

// Txt creates an escaped text node.
func Txt(s string) *Node { return &Node{Text: s} }

// RawHTML creates a text node that is emitted verbatim.
func RawHTML(s string) *Node { return &Node{Text: s, Raw: true} }

// SetAttr sets an attribute, normalising shorthand and dashes the way
// dominate's clean_attribute does.
func (n *Node) SetAttr(key, value string) *Node {
	if n.Attrs == nil {
		n.Attrs = map[string]string{}
	}
	n.Attrs[normalizeAttr(key)] = value
	return n
}

// Add appends children and returns the receiver.
func (n *Node) Add(kids ...*Node) *Node {
	n.Kids = append(n.Kids, kids...)
	return n
}

// Prepend inserts a child before all others.
func (n *Node) Prepend(kid *Node) *Node {
	n.Kids = append([]*Node{kid}, n.Kids...)
	return n
}

// findAll returns every descendant element with the given tag name, in
// depth-first order.
func (n *Node) findAll(tag string) []*Node {
	var out []*Node
	var rec func(*Node)
	rec = func(p *Node) {
		for _, c := range p.Kids {
			if c.Tag == "" {
				continue
			}
			if c.Tag == tag {
				out = append(out, c)
			}
			rec(c)
		}
	}
	rec(n)
	return out
}

// Find returns the first descendant with the given tag, or nil.
func (n *Node) Find(tag string) *Node {
	if all := n.findAll(tag); len(all) > 0 {
		return all[0]
	}
	return nil
}

// FindClass returns the first descendant whose class attribute equals cls.
func (n *Node) FindClass(cls string) *Node {
	var found *Node
	var rec func(*Node)
	rec = func(p *Node) {
		if found != nil {
			return
		}
		for _, c := range p.Kids {
			if c.Tag == "" {
				continue
			}
			if c.Attrs["class"] == cls {
				found = c
				return
			}
			rec(c)
			if found != nil {
				return
			}
		}
	}
	rec(n)
	return found
}

// Render returns the compact HTML for the node.
func (n *Node) Render() string {
	var b strings.Builder
	n.render(&b)
	return b.String()
}

func (n *Node) render(b *strings.Builder) {
	if n == nil {
		return
	}
	if n.Tag == "" {
		if n.Raw {
			b.WriteString(n.Text)
		} else {
			b.WriteString(escape(n.Text))
		}
		return
	}

	b.WriteByte('<')
	b.WriteString(n.Tag)

	keys := make([]string, 0, len(n.Attrs))
	for k := range n.Attrs {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		b.WriteByte(' ')
		b.WriteString(k)
		b.WriteString(`="`)
		b.WriteString(escape(n.Attrs[k]))
		b.WriteByte('"')
	}
	b.WriteByte('>')

	if singleTags[n.Tag] {
		return
	}
	for _, c := range n.Kids {
		c.render(b)
	}
	b.WriteString("</")
	b.WriteString(n.Tag)
	b.WriteByte('>')
}

// escape mirrors dominate.util.escape (which is the stdlib cgi.escape): it
// escapes &, <, > and " (but not ').
func escape(s string) string {
	s = strings.ReplaceAll(s, "&", "&amp;")
	s = strings.ReplaceAll(s, "<", "&lt;")
	s = strings.ReplaceAll(s, ">", "&gt;")
	s = strings.ReplaceAll(s, `"`, "&quot;")
	return s
}

func normalizeAttr(key string) string {
	switch key {
	case "cls", "className", "class_name", "klass":
		return "class"
	case "fr", "html_for", "htmlFor":
		return "for"
	}
	if strings.HasPrefix(key, "data_") || strings.HasPrefix(key, "aria_") {
		return strings.ToLower(strings.ReplaceAll(key, "_", "-"))
	}
	if strings.HasPrefix(key, "_") {
		return key[1:]
	}
	return key
}

// singleTags are rendered without a closing tag, matching dominate's is_single.
var singleTags = map[string]bool{
	"area": true, "base": true, "br": true, "col": true, "command": true,
	"embed": true, "hr": true, "img": true, "input": true, "keygen": true,
	"link": true, "meta": true, "param": true, "source": true, "track": true,
	"wbr": true,
}
